### ISSUE TITLE
Is this plugin deprecated now that it is being removed from Timber 2.0?

### ISSUE THREAD

**Issue by columbian-chris** [Upstatement/routes#29]
https://timber.github.io/docs/v2/upgrade-guides/2.0/#removed-routes

Since routing has been taken out of Timber 2.0, does that mean this plugin will no longer be maintained?  Can I still use this plugin with Timber 2.0 or is it no longer compatible?

**Comment by jarednova** [comment]
@columbian-chris you should be good to keep using w Timber 2.0. We're simply removing the (long deprecated) `Timber::add_route()` methods, etc. so you'll need to call `Routes` directly (along with including it via Composer, etc.)

**Comment by columbian-chris** [comment]
I know I'm not writing this in Timber repo right now, but it might be great if this was included in the Timber 2.0 docs! :)
