### ISSUE TITLE
Bad phpdoc

### ISSUE THREAD

**Issue by dimitriBouteille** [Upstatement/routes#30]
I think there is an error with the documentation of the function `Routes::load(...)`

```php
* @param array $template           A php file to load (ex: 'single.php')
* @param array|bool $tparams       An array of data to send to the php file. Inside the php file
...
```

The `$template` variable is not I think of type `array` but of type `string`, so the phpdoc must be :

```php
* @param string $template           A php file to load (ex: 'single.php')
* @param array|bool $tparams     An array of data to send to the php file. Inside the php file
...
```

I have this error : `Expected parameter of type 'array', 'string' provided` :( 

![Capture d’écran du 2021-04-19 00-59-13](https://user-images.githubusercontent.com/34821762/115163642-861f1300-a0aa-11eb-963d-dcf3fc32be0c.png)

**Comment by dimitriBouteille** [comment]
No news @jarednova

**Comment by jarednova** [comment]
@dimitriBouteille submit a PR!

**Comment by dimitriBouteille** [comment]
Already fix in this commit : https://github.com/Upstatement/routes/commit/9064f968da09d1714f26a9d1623dae909be49907#diff-7ca92ebfc8afde64bb3b92b501148a42ef43d55adc661f288a70933cc21e829d
