### ISSUE TITLE
Fatal error in WordPress 4.6

### ISSUE THREAD

**Issue by stewarty** [Upstatement/routes#5]
WordPress 4.6 now includes Ryan McCue's Requests Library.

When using Routes it is possible to get a Fatal Error as you are also including this Library but in an older version it would seem?  Anyway, The `Request_Response` Classes aren't the same.  Yours is getting used in preference to the included one.  This causes the `is_redirect()` method to be reported as missing and WP has a fatal crash.

Fix in the meantime is to just delete the Requests Folder in vendor

**Comment by jarednova** [comment]
Thanks for the heads-up on this @stewarty, sounds like I need to do some 4.6 testing! Could you point me to where in the code the conflicting classes are? Is this something in this repo, or one of the dependencies I'm using? (like AltoRouter)

**Comment by stewarty** [comment]
It's in your dependencies. rmmcue/requests

Is it actually being used?

The Resquest_Response class is conflicting!

**Comment by jarednova** [comment]
Hi @stewarty, I'm sorry but I'm not able to find `rmmcue/requests` in the dependencies or elsewhere in the code. The [dependencies](https://github.com/Upstatement/routes/blob/master/composer.json) I'm using are just Altorouter, Composer and PHP. Can you point to where exactly this exists? Is this the current master or a past version of this repo?

**Comment by stewarty** [comment]
Gottya  - its actually in wp-cli

https://github.com/wp-cli/wp-cli/blob/master/composer.json#L17

**Comment by jarednova** [comment]
I will crush them.
