### ISSUE TITLE
AltoRouter version limitation

### ISSUE THREAD

**Issue by JRWillis** [Upstatement/routes#8]
Our application has a requirement of AltoRouter at version 1.2.0, however, this package is limiting the version to 1.1.0.

We're using Timber, which is including Upstatement/routes, and it's in WordPress where we have that higher dependancy on AltoRouter - because we are using our own routing package.

## Suggested fix

I suggest we allow any version < 2.0.0, and I have added a pull request for this fix.

**Comment by jarednova** [comment]
Close by #9 and #10
